### ISSUE TITLE
Store Hours don't work properly with EST timezones

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/EDD-Store-Hours#4]
### Expected
When WP timezone is set to EST, Toronto or UTC -5, short should be closed or open based on that timezone.

### Actual
CST Timezone works as expected but when WP is set to EST, Toronto or UTC -5, store is not open/closed during the expected time period. Change the house a couple hours forward or backwards doesn't help, the Store House current time appears to be drastically different than the WordPress current time.

![screen_shot_2019-02-05_at_4_37_33_pm](https://user-images.githubusercontent.com/30910807/52309323-64239500-2965-11e9-8594-839d349610c3.png)
![screen shot 2019-02-05 at 4 43 13 pm](https://user-images.githubusercontent.com/30910807/52309329-684fb280-2965-11e9-80d1-3574d8ae0829.png)

https://secure.helpscout.net/conversation/765542870/99553?folderId=1847242

**Comment by dgoldak** [comment]
This issue was reported by a customer but reproduced on my test site.

**Comment by dgoldak** [comment]
I haven't tested in a earlier version of PHP but both the customer and I are running 7.0+.

**Comment by dgoldak** [comment]
I did test 5.6 with the same results, EST still doesn't work.

**Comment by dgoldak** [comment]
Update, CST doesn't seem to work either, as I originally thought.

**Comment by cklosowski** [comment]
Ok, now that we have the .org repo controlled, and I was able to back port the 1.1.0 version that was on .org to our repo, I can move forward with trying to fix this.

**Comment by cklosowski** [comment]
@dgoldak this is ready for testing.

**Comment by dgoldak** [comment]
@cklosowski, it's still not working properly for me.

Would it be possible to add a current time and an indication of store open/closed on the page in the event someone isn't using the admin bar option.

**Comment by dgoldak** [comment]
I've tested a couple timezones and so far so good! I'm thinking I'll spend a few more minutes testing than send the fix to the customer to test and confirm it works for them over a couple days.

**Comment by dgoldak** [comment]
Update, UTC+ timezones are currently not working. It happens that while I'm testing UTC+ happens to be the next day (Wednesday) instead of being currently Tuesday in America.

<img width="854" alt="screen shot 2019-02-19 at 4 36 46 pm" src="https://user-images.githubusercontent.com/30910807/53053912-5d6a4700-3468-11e9-9ed6-25461ca5ba2b.png">

I'll plan retest tomorrow morning when UTC+ is the same day as my timezone.

**Comment by cklosowski** [comment]
Ok fixed this up. It wasn't an issue with UTC+ times, but was due to how times in the `1200 - 1259` range were being handled.

**Comment by dgoldak** [comment]
Let me know if you want a separate issue for this but customer reported that Store Hours doesn't work properly between 11:59 to 12:01. 

For example, his store was set to Open but says during those couple minutes it was closed.
![bug](https://user-images.githubusercontent.com/30910807/53497050-ee44b200-3a68-11e9-8ea2-943d3574e3ec.jpg)

I'm not sure how to replicate this behavior on demand, any suggestions if needed?

**Comment by cklosowski** [comment]
@dgoldak that's because he's not defining an open AND close time. If he specifies an open time and a close time on the days it should be able to determine that. One of the checks here is that if it's before open and after close it is marked as close, but when we have no time to base it off of, one of those conditions fails.

Replicate by using his behavior of not defining an open and close time and let me know.

**Comment by dgoldak** [comment]
Opened a new issue to address "customer reported that Store Hours doesn't work properly between 11:59 to 12:01". https://github.com/easydigitaldownloads/EDD-Store-Hours/issues/7

@cklosowski The original timezone issue is resolve and customer has been running fix, so this issue should be able to be closed.
